# Generated by Django 3.1.3 on 2021-01-09 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_uuid',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
